apiVersion: apps/v1
kind: Deployment
metadata:
  name: container1-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: container1-deployment
  template:
    metadata:
      labels:
        app: container1-deployment
    spec:
      volumes:
        - name: shared-volume
          persistentVolumeClaim:
            claimName: container-pvc
      containers:
        - name: container1
          image: us-central1-docker.pkg.dev/western-notch-453423-p9/csci5409/container1:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 6000
          volumeMounts:
            - mountPath: /siddik_PV_dir
              name: shared-volume

---

apiVersion: v1
kind: Service
metadata:
  name: application-deployment-service
spec:
  selector:
    app: application-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 6000
      name: http
  type: LoadBalancer 
