apiVersion: apps/v1
kind: Deployment

metadata:
  name: image-pod-1

spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-container-1

  template:
    metadata:
      labels:
        app: kube-container-1

    spec:
      containers:
        - name: container1
          image: "us-central1-a-docker.pkg.dev/western-notch-453423-p9/csci5409/container1"
          imagePullPolicy: Always
          ports:
            - containerPort: 6000
          volumeMounts:
            - name: kube-storage
              mountPath: /siddik_PV_dir

      volumes:
        - name: kube-storage
          persistentVolumeClaim:
            claimName: kube-storage